# http://tex.stackexchange.com/questions/11710/specify-output-directory-when-using-latexmk
$pdflatex="pdflatex -interaction nonstopmode %O %S";
$out_dir = 'out';
$pdf_mode = 1;
$pdf_previewer = 'xdg-open';

@default_files = ('0[0-9]*tex');

$ENV{TEXINPUTS} .=':media';
$ENV{TEXINPUTS} .=':slides';
$ENV{TEXINPUTS} .=':code';
$ENV{TEXINPUTS} .=':vids';
$HOME = $ENV{HOME};
$ENV{TEXINPUTS} .=':$HOME/research/presentations/slides';
$ENV{TEXINPUTS} .=':$HOME/research/presentations/slides/snippets';
$ENV{TEXINPUTS} .=':$HOME/research/presentations/slides/style';
$ENV{TEXINPUTS} .=':$HOME/research/presentations/slides/media';
